import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'its_project.settings')
django.setup()

from domain.models import Concept
from learning.models import Question, QuestionOption

def create_mc_question(concept_slug, statement, options_data, explanation, difficulty=2, hint=''):
    try:
        concept = Concept.objects.get(slug=concept_slug)
        q, created = Question.objects.get_or_create(
            concept=concept,
            statement=statement,
            defaults={
                'question_type': 'multiple_choice',
                'explanation': explanation,
                'difficulty': difficulty,
                'hint': hint
            }
        )
        if created:
            for i, (text, is_correct) in enumerate(options_data):
                QuestionOption.objects.create(question=q, text=text, is_correct=is_correct, order=i)
    except Exception as e:
        print(f"Erro no conceito {concept_slug}: {e}")

def create_tf_question(concept_slug, statement, correct_answer, explanation, difficulty=2, hint=''):
    try:
        concept = Concept.objects.get(slug=concept_slug)
        q, created = Question.objects.get_or_create(
            concept=concept,
            statement=statement,
            defaults={
                'question_type': 'true_false',
                'explanation': explanation,
                'difficulty': difficulty,
                'hint': hint
            }
        )
        if created:
            QuestionOption.objects.create(question=q, text='Verdadeiro', is_correct=correct_answer, order=0)
            QuestionOption.objects.create(question=q, text='Falso', is_correct=not correct_answer, order=1)
    except Exception as e:
        print(f"Erro TF no conceito {concept_slug}: {e}")

print("Inserindo novas questões...")

# --- 1. receita-e-despesa ---
create_tf_question('receita-e-despesa', 'O aluguel da sua residência é classificado primariamente como uma despesa variável, uma vez que o contrato sofre reajustes anuais atrelados à inflação.', False, 'Falso. Embora sofra reajustes no longo prazo, no orçamento mensal o aluguel é inelástico e mandatório, sendo classificado como uma Despesa Fixa.', 1)
create_mc_question('receita-e-despesa', 'Um investidor decide alugar um quarto vazio em sua casa pelo Airbnb, gerando renda sem precisar estar presente ativamente durante a estadia. Esta nova fonte de dinheiro classifica-se como:', [('Receita Bruta Ativa', False), ('Receita Líquida Fixa', False), ('Receita Passiva', True), ('Despesa Recuperável', False)], 'A renda de aluguéis e dividendos onde a troca de tempo por dinheiro não é linear caracteriza a chamada Receita Passiva.', 2)
create_mc_question('receita-e-despesa', 'Uma família reduz as saídas a restaurantes para pagar mais rápido o financiamento da casa. Eles mexeram em qual frente orçamentária?', [('Receitas Passivas', False), ('Despesas Inelásticas', False), ('Despesas Variáveis (Elásticas)', True), ('Fluxo de Caixa Livre', False)], 'Restaurantes compõem despesas variáveis discricionárias, as mais fáceis de cortar no curto prazo sem gerar inadimplência.', 1)
create_mc_question('receita-e-despesa', 'A distinção fundamental para projetar a capacidade de aporte mensal (Free Cash Flow) exige que o dimensionamento dos gastos mensais não exceda:', [('O Teto do INSS', False), ('A Receita Bruta Nominal', False), ('A Receita Líquida (pós-impostos)', True), ('O Limite do Cartão de Crédito', False)], 'A métrica que interessa é o que cai efetivamente na conta. Planejar gastos com base no salário bruto levará invariavelmente ao desequilíbrio.', 2)

# --- 2. orcamento-pessoal ---
create_tf_question('orcamento-pessoal', 'Na metodologia Orçamento Base-Zero (ZBB), o investidor pode manter saldos sem destinação clara ("sobras") na conta corrente para eventuais mimos do dia a dia.', False, 'Falso. A premissa do ZBB é que todo centavo ganhe um "trabalho" antes do mês começar (inclusive o lazer tem uma rubrica pré-definida), deixando a soma Receitas - Despesas exata a R$ 0.', 2)
create_mc_question('orcamento-pessoal', 'Na regra orçamentária 50/30/20, os 20% representam estrategicamente:', [('Lazer e Entretenimento', False), ('Aluguel e Moradia', False), ('Poupança, Investimentos e Redução de Dívidas onerosas', True), ('Alimentação básica', False)], 'O terço final da regra foca na formação de patrimônio e saneamento financeiro, garantindo crescimento no longo prazo.', 1)
create_mc_question('orcamento-pessoal', 'O princípio "Pay Yourself First" altera fundamentalmente a dinâmica temporal de qual elemento da gestão financeira?', [('O pagamento de impostos federais', False), ('A aplicação dos investimentos mensais', True), ('O pagamento do aluguel', False), ('O giro do cartão de crédito', False)], 'Ele força a aplicação financeira a ocorrer no mesmo dia em que o salário é recebido, não deixando para o final do mês onde corre o risco de ser gasto impulsivamente.', 2)
create_tf_question('orcamento-pessoal', 'O orçamento pessoal deve tratar os gastos recorrentes com educação e saúde familiar como despesas variáveis e discricionárias.', False, 'Falso. Saúde e Educação base são pilares inelásticos e essenciais, não devendo flutuar discricionariamente.', 1)

# --- 3. planejamento-financeiro ---
create_tf_question('planejamento-financeiro', 'Na "Fase de Acumulação" do ciclo de vida (20-45 anos), o crescimento do patrimônio é provido majoritariamente pelo volume de aportes suados, e não pelos juros compostos.', True, 'Verdadeiro. No começo do ciclo, a base de capital é baixa. O motor principal do enriquecimento são os aportes altos provenientes do aumento do seu salário/negócio.', 2)
create_mc_question('planejamento-financeiro', 'Uma meta que diz "Desejo ter muito dinheiro para viajar pela Ásia algum dia" falha drasticamente no método SMART por carecer de:', [('Significado e Relevância', False), ('Especificidade, Mensuração e Limite Temporal (Tempo)', True), ('Atingibilidade sistêmica', False), ('Impostos embutidos', False)], 'O SMART exige "R$ 30 mil" (M), para "Ir ao Japão" (S), em "Novembro de 2026" (T).', 1)
create_mc_question('planejamento-financeiro', 'Um indivíduo de 65 anos, recém-aposentado e na Fase de Usufruição, deveria ter o seguinte objetivo principal de planejamento da carteira:', [('Aumentar exponencialmente o risco para gerar altos aportes', False), ('Buscar dividendos (Geração de Caixa) e preservação do poder de compra contra a inflação', True), ('Alavancar-se em dívidas para aquisição de imóveis rurais', False), ('Investir 100% em ações de micro empresas de tecnologia', False)], 'Nesta idade a prioridade é transformar o bolo patrimonial acumulado num salário estável e protegido.', 2)
create_mc_question('planejamento-financeiro', 'Qual das seguintes metas não obedece ao critério "Alcançável" (Achievable) do modelo SMART para um jovem estagiário ganhando R$ 1.500/mês?', [('Juntar R$ 3.000 para a reserva em 2 anos', False), ('Economizar R$ 100/mês em tarifas', False), ('Comprar um carro esportivo de R$ 300.000 em 18 meses usando poupança', True), ('Pagar o curso de R$ 5.000 financiando em 12 vezes controladas', False)], 'Salvo milagres, poupar R$ 300 mil em 18 meses requereria R$ 16.600/mês líquidos. Inviável matematicamente, quebrando a meta no "A" do SMART.', 1)

# --- 4. reserva-de-emergencia ---
create_tf_question('reserva-de-emergencia', 'Para maximizar os ganhos da reserva de emergência, é adequado comprar ações pagadoras de dividendos, pois fornecem uma renda extra constante.', False, 'Falso. A reserva jamais visa lucro agressivo. Ela foca em Liquidez (acesso no mesmo dia) e Segurança. Ações possuem risco sistêmico e a reserva poderia estar derretendo no dia que a emergência ocorrer.', 2)
create_mc_question('reserva-de-emergencia', 'O cálculo do custo de vida ideal para a reserva deve omitir qual tipo de despesa?', [('Aluguel de Moradia', False), ('Saúde e Alimentação Base', False), ('Gastos discricionários excessivos, como hotéis luxuosos e viagens internacionais recorrentes', True), ('Seguro do Carro e IPTU', False)], 'A reserva garante sobrevivência estrutural, focando nos custos fixos inelásticos, expurgando caprichos no cálculo.', 1)
create_mc_question('reserva-de-emergencia', 'Qual o múltiplo referencial adequado de capital de Reserva de Emergência para um empreendedor ou autônomo PJ com renda altamente instável?', [('1 Mês de custos', False), ('3 a 6 Meses de custos', False), ('12 a 18 Meses de custos', True), ('Não precisam de reserva, usam limite empresarial', False)], 'A instabilidade exige uma proteção (colchão) muito maior que a de um servidor público estável (3 a 6 meses).', 2)
create_mc_question('reserva-de-emergencia', 'Dentre os ativos abaixo, indique o único perfeitamente aderente aos requisitos rigorosos (Liquidez e Baixa Volatilidade) de uma Reserva de Emergência Tier 2:', [('Fundos Imobiliários', False), ('Ouro Físico', False), ('CDBs de Liquidez Diária a 100% do CDI emitidos por Grandes Bancos ou Tesouro Selic', True), ('Tesouro IPCA+ com vencimento em 2045', False)], 'O CDB Diário e Selic não sofrem marcação a mercado agressiva e permitem resgate sem deságio.', 1)

# --- 5. porcentagem ---
create_tf_question('porcentagem', 'Se uma ação cai 20% e, no mês seguinte, sobe 20%, o valor dela volta a ser perfeitamente o mesmo do início da operação.', False, 'Falso. Ex: Cai 20% de 100 = 80. Sobe 20% de 80 = 96. Fatores de Variação (0.80 * 1.20 = 0.96). Patrimônio teve perda real de 4%.', 2)
create_mc_question('porcentagem', 'O "Fator de Acréscimo" e o "Fator de Desconto" de uma variação de 30% são, respectivamente:', [('1.30 e 0.30', False), ('1.30 e 0.70', True), ('130 e 70', False), ('0.30 e -0.30', False)], 'Acréscimo: (1 + 0.30) = 1.30. Desconto: (1 - 0.30) = 0.70. A multiplicação direta destes fatores no capital gera os resultados absolutos.', 1)
create_mc_question('porcentagem', 'Qual é a representação numérica correta na "forma unitária" (decimal) necessária para jogar na calculadora financeira um rendimento de "3,5% ao mês"?', [('3.50', False), ('0.35', False), ('0.035', True), ('35', False)], 'A forma decimal exige divisão por 100. 3.5 / 100 = 0.035.', 1)
create_tf_question('porcentagem', 'Múltiplas variações percentuais sucessivas de descontos em compras são sempre somadas linearmente. Ex: Desconto de 10% seguido de 5% no caixa resulta em exatamente 15% de desconto total.', False, 'Falso. Variações sucessivas são compostas (fatores multiplicados). O fator é (0.90 * 0.95 = 0.855), o que dá um desconto real de 14,5%.', 3)

# --- 6. juros-simples ---
create_mc_question('juros-simples', 'Qual é a característica geométrica principal que diferencia o patrimônio rendendo a Juros Simples num gráfico de tempo (Eixo X) vs Montante (Eixo Y)?', [('Forma uma parábola ascendente explosiva', False), ('Forma uma reta linear diagonal perfeita', True), ('Forma um zigue-zague com volatilidade', False), ('A linha do patrimônio afunda verticalmente', False)], 'Como o crescimento é sempre o mesmo valor constante a cada período (capital base fixo), a função é de 1º Grau (Reta).', 1)
create_tf_question('juros-simples', 'Nos juros simples, não importa quantos anos o dinheiro fique aplicado, o capital gerador do rendimento (a base de cálculo) do Ano 10 será rigorosamente o mesmo do Ano 1.', True, 'Verdadeiro. O rendimento ganho nos anos anteriores é descartado do cálculo, não gerando "juros sobre juros".', 2)
create_mc_question('juros-simples', 'Se você emprestar R$ 2.000,00 à taxa de juros simples de 5% ao mês, qual o valor exato, apenas em JUROS (excluindo principal), que você terá recebido ao final de 3 meses?', [('R$ 100,00', False), ('R$ 315,25', False), ('R$ 300,00', True), ('R$ 2.300,00', False)], 'J = C * i * t -> J = 2000 * 0.05 * 3 = 100 * 3 = 300.', 2)
create_mc_question('juros-simples', 'Qual mercado ainda faz forte e exclusivo uso diário de Juros Simples para suas operações financeiras tradicionais?', [('Fundos Imobiliários e de Ações', False), ('Descontos de Duplicatas e Cheques no sistema Bancário/Comercial de Varejo de curtíssimo prazo', True), ('Tesouro Direto', False), ('Previdência Privada e Fundos Multimercado', False)], 'A antecipação de boletos/duplicatas entre fornecedores e factorings utiliza o chamado Desconto Comercial Simples por praticidade legal.', 2)

# --- 7. juros-compostos ---
create_tf_question('juros-compostos', 'Na equação de Juros Compostos (FV = PV * (1+i)^t), o principal fator de alavancagem que gera a curva exponencial é o tamanho brutal do aporte inicial (PV), e não o tempo (t).', False, 'Falso. O elemento "tempo" (t) atua como potência, sendo incrivelmente mais destrutivo e explosivo na fórmula geométrica que um mero aumento linear do Capital (PV).', 2)
create_mc_question('juros-compostos', 'O mecanismo da "Bola de Neve" dos juros compostos deve seu sucesso estritamente ao fenômeno matemático onde:', [('A taxa básica de juros sobe todo ano pelo Banco Central.', False), ('Os rendimentos gerados no primeiro período são adicionados ao capital principal, servindo como a nova base ampliada para incidência da taxa no segundo período.', True), ('Os aportes são cortados à metade ao longo do tempo.', False), ('O governo abate os impostos progressivamente.', False)], 'A base do cálculo incha sistematicamente porque todo lucro imediatamente vira capital principal para render no próximo ciclo (juros sobre juros).', 1)
create_mc_question('juros-compostos', 'Sobre o ciclo longo de investimentos (30 anos) com juros compostos, a maior parte do Montante Final amealhado na conta de um investidor consistente provirá originariamente:', [('Do capital bruto retirado do próprio bolso (esforço do trabalho).', False), ('Dos rendimentos compostos exponenciais superando e esmagando os valores aplicados pelo investidor.', True), ('Da herança e transferências institucionais do governo', False), ('Das deduções tributárias legais', False)], 'Em décadas sob juros compostos, o montante de "lucro ganho" frequentemente representa 60% a 80% do saldo total, aniquilando a contribuição direta inicial do próprio bolso.', 3)
create_mc_question('juros-compostos', 'Por que as dívidas do rotativo do Cartão de Crédito e do Cheque Especial são tão letais financeiramente sob a ótica dos juros compostos?', [('Porque as administradoras não permitem quitar antes de 5 anos.', False), ('Porque elas carregam taxas gigantescas (ex: 15% a.m.) submetidas ao mesmo efeito exponencial de potência dos juros, criando bolas de neve de passivos incontornáveis.', True), ('Porque o imposto sobre operação financeira (IOF) é de 50%.', False), ('Porque elas operam exclusivamente sob juros simples diários.', False)], 'O cartão de crédito usa o seu maior aliado contra você. Juros compostos de 15% multiplicam a dívida assustadoramente todo mês.', 1)

# --- 8. inflacao ---
create_tf_question('inflacao', 'Em matemática financeira macroeconômica, é possível que a sua taxa de Rentabilidade Nominal (o que aparece no banco) seja de incríveis 20% e você, ainda assim, tenha ficado estruturalmente mais pobre no mesmo período.', True, 'Verdadeiro. Se a inflação do país bater 25%, seu dinheiro na conta aumentou numérico 20%, mas as coisas ficaram 25% mais caras. Você empobreceu em Termos Reais.', 2)
create_mc_question('inflacao', 'A Equação de Fisher ajustada orienta o mercado profissional na apuração do ganho verdadeiro através da correlação correta de divisão dos Fatores. Qual é a forma correta de enxergar o Lucro Real?', [('Subtrair a inflação dos juros: (Rentabilidade - IPCA)', False), ('Adicionar a Selic ao IPCA somado (Selic + Inflação)', False), ('Dividir o Fator Nominal pelo Fator Inflacionário: [(1 + Nominal) / (1 + IPCA)] - 1', True), ('Multiplicar os juros pelo IPCA: IPCA * Rentabilidade nominal', False)], 'Dividir fatores ajusta perfeitamente os desníveis compostos, dando o lucro limpo de perda de poder.', 3)
create_mc_question('inflacao', 'Qual dos indexadores abaixo é o padrão-ouro de inflação acompanhado pelo COPOM e utilizado na emissão dos Títulos do Tesouro indexados (NTN-Bs)?', [('Taxa Selic', False), ('CDI', False), ('IGP-M', False), ('IPCA (Índice Nacional de Preços ao Consumidor Amplo)', True)], 'O IPCA é a inflação oficial nacional, sendo o farol balizador das metas do governo e o pilar do Tesouro Direto atrelado à inflação.', 1)
create_mc_question('inflacao', 'Um dos efeitos perversos da inflação (corrosão sistêmica do poder de compra) é atuar como uma:', [('Injeção brutal de liquidez nas poupanças', False), ('Taxação silenciosa e oculta da riqueza de quem mantém o dinheiro estagnado, mitigando as dívidas nominais do Estado.', True), ('Reestruturação benéfica do mercado de dívida privada de curto prazo', False), ('Alavanca de compra no exterior (Deflação cambial)', False)], 'Dinheiro parado debaixo do colchão perde valor dia após dia pela diluição da expansão monetária, agindo como um tributo implícito sobre os poupadores conservadores não investidos.', 2)

# --- 9. risco-e-retorno ---
create_tf_question('risco-e-retorno', 'Títulos do Tesouro Selic no Brasil são classificados como risco zero, implicando que a volatilidade dos seus preços no mercado é extremamente baixa, logo não pagam prêmio de risco exorbitante.', True, 'Verdadeiro. Essa é a própria definição de Risco e Retorno e taxa Livre de Risco (Risk-Free). Onde há risco quase zero do Estado quebrar e calotar na própria moeda, a taxa não trará surpresas.', 1)
create_mc_question('risco-e-retorno', 'No paradigma do Trade-Off entre Risco e Retorno, promessas espetaculares de "10% ao mês garantido em contrato" em publicidade da internet caracterizam primordialmente:', [('A mágica da renda fixa incentivada por CRIs', False), ('Um indicativo vermelho de fraude estrutural e Pirâmide de Ponzi, pois desrespeita a regra áurea de que rentabilidade estratosférica incorre inerente e imenso risco não garantido.', True), ('Uma estratégia de fundos imobiliários com lajes muito alugadas', False), ('Asset Allocation em títulos americanos garantidos', False)], 'Qualquer retorno garantido não pode desviar absurdamente da Taxa Livre de Risco vigente sem embutir trapaças lógicas.', 2)
create_mc_question('risco-e-retorno', 'O Jargão "Volatilidade" indica fisicamente o que no home broker de um investidor de bolsa?', [('A liquidez de venda de balcão na corretora', False), ('A medição de Desvio Padrão do preço, ou seja, as oscilações agudas do sobe e desce das ações frente à média de rentabilidade.', True), ('A taxa diária do IR retido na fonte', False), ('O pagamento perene e tranquilo de juros contábeis sobre capital próprio', False)], 'A volatilidade diz que, embora uma ação renda muito no longo prazo, no curto prazo ela pode derreter ou subir violentamente.', 2)
create_mc_question('risco-e-retorno', 'Os investidores exigem ser compensados quando decidem abandonar a segurança do Tesouro para aportar em startups e bancos via CDB. O nome desta "taxa a mais" paga ao investidor por tomar Risco Específico ou Risco de Crédito chama-se:', [('Taxa de Custódia da B3', False), ('Spread de Liquidez', False), ('Taxa livre de arbitragem', False), ('Prêmio de Risco (Risk Premium ou Spread de Crédito)', True)], 'Prêmio é exatamente o valor a mais. O CDB paga "Selic + 3%". Esses 3% são o prêmio pelo medo e pelo risco que o investidor assume que o banco quebre.', 2)

# --- 10. investimentos ---
create_tf_question('investimentos', 'A aquisição de uma Debênture atrela você ao regime de "Sócio" da empresa privada, correndo o risco comercial do negócio e ganhando com distribuições proporcionais dos lucros líquidos do ano.', False, 'Falso. Debênture é Renda Fixa (Mercado de Dívida). O investidor se torna MERO CREDOR que emprestou dinheiro querendo de volta acrescido de juros contratuais, não tendo fração do negócio (ações).', 2)
create_mc_question('investimentos', 'Ao se associar (comprar Equity/Ações) da Companhia XYZ listada na Bolsa (B3), você terá a expectativa principal de ganhos baseada em:', [('Rendimento atrelado 100% ao IPCA cravado pelo governo ao final do IPO', False), ('Proteção inabalável contra as crises cambiais internacionais (Zero volatilidade)', False), ('Valorização de mercado das cotas (Crescimento de múltiplos) e repasse contínuo de Dividendos/JCP das atividades lucrativas da operação.', True), ('Garantia integral do saldo devolvido pelo Fundo Garantidor de Créditos (FGC) se o preço da ação desabar em crise de confiança.', False)], 'Bolsa não tem FGC. A associação confia na escalabilidade operacional da empresa que trará valor das vendas aos donos (Apreciação de Capital + Dividendos).', 2)
create_mc_question('investimentos', 'Fundos Imobiliários (FIIs) entregam um grande diferencial institucional ao investidor Pessoa Física conservador-moderado no Brasil que busca formar um "salário" recorrente através do aluguel imobiliário:', [('O principal do investimento possui seguro contra inflação', False), ('A isenção absoluta de Imposto de Renda sobre os proventos (dividendos mensais) repassados pelas administradoras e alta liquidez na venda.', True), ('Rendimento indexado com trava mínima assegurada pela CVM no regulamento.', False), ('Alavancagem garantida das administradoras nos laudos de incorporação.', False)], 'Os aluguéis (proventos) isentos são o maior atrativo, superando brutalmente a compra de um imóvel direto e recebimento de aluguel (que bate forte na malha fina do IRPF de alíquota 27,5%).', 2)
create_mc_question('investimentos', 'Avaliar o "Perfil de Suitability" atua regulatoriamente com qual propósito primário?', [('Filtrar investidores milionários no banco de retalho', False), ('Cobrar impostos adiantados dos rendimentos futuros de Day Trade.', False), ('Averiguar formalmente a Tolerância a Risco, tempo de experiência e resgate esperado do cliente, evitando que investidores super conservadores entrem em Pânico e processem as corretoras por queda em ações não informadas.', True), ('Adequar o CPF a sistemas abertos de pirâmide legal', False)], 'Adequar a carteira ao estômago psicológico e prazos do cliente (Conservador, Moderado, Arrojado) evita ruína financeira e psiquiátrica em momentos de crise sistêmica de mercado.', 1)

# --- 11. diversificacao-de-carteira ---
create_tf_question('diversificacao-de-carteira', 'Para ocorrer proteção verdadeira contra catástrofes de bolsa (Cisnes Negros), os ativos escolhidos para balanceamento de portfólio DEVEM ter Correlação Fortemente Positiva (+1.0).', False, 'Falso. Correlação positiva faz as duas pernas despencarem juntas no choque macroeconômico (Ex: Comprar Itaú e Bradesco). O hedge milagroso requer Correlação Descorrelacionada ou Negativa (Ex: Ações Locais x Dólar Ouro).', 3)
create_mc_question('diversificacao-de-carteira', 'O maior milagre da Teoria do Portfólio dita que comprar duas classes que se "odeiam" estatisticamente (correlação inversa) vai proteger os ganhos com um bônus inacreditável que é:', [('Aumentar imensamente o pagamento dos impostos da base de corretagem nos EUA', False), ('Impor travas operacionais na capacidade de venda do investidor de varejo com alavancagem sintética', False), ('Erradicar completamente todo o risco Específico (Idiossincrático) mitigando falências locais de empresas através de fundos variados, diminuindo a Volatilidade global (Risco) abaixo das métricas exclusivas, preservando todo o prêmio (retorno).', True), ('Criar garantias no FGC e Tesouro Selic que cobrem todas as perdas iminentes', False)], 'Misturar ativos descorrelacionados é o Almoço Grátis da bolsa. Você ganha retornos médios enormes e sua oscilação emocional vai pra baixo (baixo drawdown) pois uma coisa protege a queda da outra todo o tempo.', 3)
create_mc_question('diversificacao-de-carteira', 'A readequação semestral chamada "Rebalanceamento Estratégico de Carteira" comunga das teses de finanças comportamentais porque obriga a atitude psicológica anti-natural de:', [('Manter as ações congeladas eternamente para fugir do come-cotas do tesouro DI do governo', False), ('Assumir novos riscos baseados no instinto do influenciador digital do momento para pegar a ação da moda em alta acelerada.', False), ('Vender ativamente e mecanicamente uma porção dos seus ativos que explodiram em preços e estouraram o Alvo do Asset Allocation para comprar os odiados e sangrentos que estão no fundo da bacia das almas.', True), ('Acumular caixas táticos gigantes que zeram a volatilidade real de curto prazo e impõem resgates da carteira integral.', False)], 'Isso força você a seguir a regra basilar de "Comprar na Baixa e Vender na Alta" mesmo quando a mente manda pular no efeito manada (comprar em topo e vender em pânico de fundo).', 2)
create_mc_question('diversificacao-de-carteira', 'Risco Sistêmico (como a quebra do Banco Central global, Pandemias Mágicas que travam comércio e inflação global nos anos 80) em um Portfólio é classicamente conhecido como:', [('Fugaz, pois a diversificação perene mitiga o cenário macro global facilmente por stock-picking nas estatais listadas locais e debêntures incentivadas de estradas e elétricas resilientes.', False), ('Aquele risco inevitável de cauda, onde virtualmente TODAS as classes entram em choque, não mitigável pela mera pulverização (diversificação local do portfólio), afetando simultaneamente a taxa de juros global livre.', True), ('O risco atenuado por ter a conta alocada num único bancão amarelo privado e fugir da corretora de shoppings local.', False), ('Risco isento e dedutível na declaração completa do PGBL ao final do encerramento da sub-escrituração da conta tributável do passivo.', False)], 'Risco Específico se anula diversificando ações. Risco Sistêmico (Cisne Negro generalizado) só se domina saindo com proteções sofisticadas de cauda (Hedge) ou alocações ultra-internacionais (Safe Havens e Commodities Físicas Ouro).', 3)

print("✅ Mais 44 questões avançadas adicionadas com sucesso!")
