# Generated by Django 5.1.4 on 2026-06-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Múltipla Escolha'), ('true_false', 'Verdadeiro/Falso'), ('fill_blank', 'Preenchimento'), ('math_problem', 'Problema Matemático'), ('case_study', 'Estudo de Caso')], max_length=20, verbose_name='Tipo')),
                ('statement', models.TextField(verbose_name='Enunciado')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explicação')),
                ('difficulty', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')], default=1, verbose_name='Dificuldade')),
                ('hint', models.TextField(blank=True, default='', verbose_name='Dica')),
                ('correct_answer', models.CharField(blank=True, default='', max_length=500, verbose_name='Resposta Correta')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='domain.concept')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['concept', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texto')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correta')),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.question')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('num_questions', models.IntegerField(default=5, verbose_name='Número de Questões')),
                ('time_limit_minutes', models.IntegerField(default=15, verbose_name='Tempo Limite (min)')),
                ('is_adaptive', models.BooleanField(default=True, verbose_name='Adaptativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='domain.concept')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Pontuação (%)')),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='domain.concept')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Tentativa de Quiz',
                'verbose_name_plural': 'Tentativas de Quiz',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Resposta do Aluno')),
                ('result', models.CharField(choices=[('correct', 'Correta'), ('partial', 'Parcialmente Correta'), ('incorrect', 'Incorreta')], max_length=10, verbose_name='Resultado')),
                ('hint_used', models.BooleanField(default=False, verbose_name='Usou Dica')),
                ('time_seconds', models.IntegerField(default=0, verbose_name='Tempo (s)')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='student.studentprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.question')),
                ('quiz_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='learning.quizattempt')),
            ],
            options={
                'verbose_name': 'Tentativa',
                'verbose_name_plural': 'Tentativas',
                'ordering': ['-created_at'],
            },
        ),
    ]
