# Generated by Django 5.1.4 on 2026-06-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(default='📚', max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='Cor')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conceito',
                'verbose_name_plural': 'Conceitos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo Teórico')),
                ('practical_examples', models.TextField(blank=True, default='', verbose_name='Exemplos Práticos')),
                ('key_points', models.TextField(blank=True, default='', verbose_name='Pontos-Chave')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('estimated_minutes', models.IntegerField(default=15, verbose_name='Tempo Estimado (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='domain.concept')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['concept', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ConceptPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='domain.concept', verbose_name='Conceito')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='domain.concept', verbose_name='Pré-requisito')),
            ],
            options={
                'verbose_name': 'Pré-requisito',
                'verbose_name_plural': 'Pré-requisitos',
                'unique_together': {('concept', 'prerequisite')},
            },
        ),
    ]
