# Generated by Django 5.1.4 on 2026-06-14 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('expert', 'Expert')], default='iniciante', max_length=20, verbose_name='Nível')),
                ('overall_progress', models.FloatField(default=0.0, verbose_name='Progresso Geral (%)')),
                ('total_study_minutes', models.IntegerField(default=0, verbose_name='Tempo Total de Estudo (min)')),
                ('total_questions_answered', models.IntegerField(default=0, verbose_name='Total de Questões Respondidas')),
                ('total_correct_answers', models.IntegerField(default=0, verbose_name='Total de Respostas Corretas')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Dias Consecutivos')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Aluno',
                'verbose_name_plural': 'Perfis dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Descrição')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Data Alvo')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Meta de Aprendizagem',
                'verbose_name_plural': 'Metas de Aprendizagem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Duração (min)')),
                ('activity_type', models.CharField(default='lesson', max_length=20, verbose_name='Tipo de Atividade')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='domain.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Sessão de Estudo',
                'verbose_name_plural': 'Sessões de Estudo',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.FloatField(default=0.0, verbose_name='Nível de Domínio (%)')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='Dominado')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Acertos')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='domain.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_masteries', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Domínio de Conceito',
                'verbose_name_plural': 'Domínios de Conceitos',
                'unique_together': {('student', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_lesson', 'Primeira Aula'), ('concept_mastered', 'Conceito Dominado'), ('perfect_quiz', 'Quiz Perfeito'), ('streak_3', '3 Dias Consecutivos'), ('streak_7', '7 Dias Consecutivos'), ('streak_30', '30 Dias Consecutivos'), ('all_basics', 'Conceitos Básicos'), ('half_done', 'Metade do Caminho'), ('all_done', 'Conclusão Total'), ('simulation_pro', 'Mestre das Simulações'), ('speed_learner', 'Aprendiz Rápido'), ('persistent', 'Persistente')], max_length=30, verbose_name='Tipo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='Ícone')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Conquistado em')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'unique_together': {('student', 'achievement_type')},
            },
        ),
    ]
