# Generated by Django 5.1.4 on 2026-06-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_type', models.CharField(choices=[('budget', 'Orçamento Mensal'), ('emergency_fund', 'Reserva de Emergência'), ('compound_interest', 'Juros Compostos'), ('investment', 'Investimentos'), ('financial_plan', 'Planejamento Financeiro')], max_length=20)),
                ('parameters', models.JSONField(default=dict, verbose_name='Parâmetros')),
                ('results', models.JSONField(default=dict, verbose_name='Resultados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Resultado de Simulação',
                'verbose_name_plural': 'Resultados de Simulações',
                'ordering': ['-created_at'],
            },
        ),
    ]
